import { useState } from "react";
import { BookOpen, Edit3, Send, Tags, Trash2 } from "lucide-react";
import { AdminShell } from "@/components/AdminShell";
import { AdminPageHeader } from "@/components/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { QueryEmpty, QueryError, QueryLoading } from "@/components/QueryState";
import { humanizeError } from "@/lib/admin";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

type DreamForm = { id?: number; categoryId: string; slug: string; title: string; summary: string; meaning: string; luckyNumbers: string; imageUrl: string; status: "draft" | "published" | "archived" };
const blankDream = (): DreamForm => ({ categoryId: "none", slug: "", title: "", summary: "", meaning: "", luckyNumbers: "", imageUrl: "", status: "draft" });

export default function AdminDreams() {
  const { user, loading } = useAuth(); const canQueryAdmin = !loading && user?.role === "admin";
  const utils = trpc.useUtils(); const categories = trpc.adminContent.categories.list.useQuery(undefined, { enabled: canQueryAdmin }); const dreams = trpc.adminContent.dreams.list.useQuery(undefined, { enabled: canQueryAdmin });
  const [form, setForm] = useState<DreamForm>(blankDream); const [categoryName, setCategoryName] = useState(""); const [categorySlug, setCategorySlug] = useState(""); const [error, setError] = useState<string | null>(null);
  const categoryCreate = trpc.adminContent.categories.create.useMutation({ onSuccess: () => { setCategoryName(""); setCategorySlug(""); utils.adminContent.categories.list.invalidate(); utils.adminContent.overview.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const create = trpc.adminContent.dreams.create.useMutation({ onSuccess: () => { setForm(blankDream()); setError(null); utils.adminContent.dreams.list.invalidate(); utils.adminContent.overview.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const update = trpc.adminContent.dreams.update.useMutation({ onSuccess: () => { setForm(blankDream()); setError(null); utils.adminContent.dreams.list.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const setStatus = trpc.adminContent.dreams.setStatus.useMutation({ onSuccess: () => { utils.adminContent.dreams.list.invalidate(); utils.adminContent.overview.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError(null); const payload = { ...form, categoryId: form.categoryId === "none" ? null : Number(form.categoryId) }; if (form.id) update.mutate({ ...payload, id: form.id }); else create.mutate(payload); };
  return <AdminShell><AdminPageHeader eyebrow="DREAM1000 LIBRARY" title="梦境与分类管理" description="分类决定公开筛选方式；Dream1000 条目可先保存为草稿，再由管理员发布或下架。" />
    {error ? <p className="mb-5 rounded-lg border border-red-300/25 bg-red-300/10 p-3 text-sm text-red-100">{error}</p> : null}
    <section className="grid gap-6 xl:grid-cols-[.8fr_1.6fr]"><div className="admin-card p-5"><div className="flex items-center gap-2"><Tags className="h-5 w-5 text-lime-200" /><h2 className="font-bold text-white">新增分类</h2></div><form onSubmit={event => { event.preventDefault(); categoryCreate.mutate({ slug: categorySlug, name: categoryName }); }} className="mt-5 space-y-4"><div><Label>分类名称</Label><Input required value={categoryName} onChange={event => setCategoryName(event.target.value)} className="admin-input mt-2" placeholder="例如：自然" /></div><div><Label>分类标识</Label><Input required value={categorySlug} onChange={event => setCategorySlug(event.target.value.toLowerCase())} className="admin-input mt-2" placeholder="例如：nature" /></div><Button disabled={categoryCreate.isPending} className="w-full bg-lime-200 text-[#09221c] hover:bg-lime-100">创建分类</Button></form><div className="mt-6 border-t border-white/10 pt-5">{categories.isLoading ? <p className="text-sm text-emerald-50/55">正在读取分类…</p> : !categories.data?.length ? <p className="text-sm text-emerald-50/55">尚无分类。请先创建分类，再为条目选择。</p> : <div className="flex flex-wrap gap-2">{categories.data.map(category => <span key={category.id} className="rounded-full border border-lime-200/15 bg-lime-200/8 px-3 py-1.5 text-xs font-semibold text-lime-100">{category.name}</span>)}</div>}</div></div>
      <div className="admin-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-lime-200" /><h2 className="font-bold text-white">{form.id ? "编辑 Dream1000 条目" : "新增 Dream1000 条目"}</h2></div>{form.id ? <Button variant="ghost" onClick={() => setForm(blankDream())} className="text-emerald-50/65 hover:text-white">取消编辑</Button> : null}</div><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2"><div><Label>分类</Label><Select value={form.categoryId} onValueChange={value => setForm({ ...form, categoryId: value })}><SelectTrigger className="admin-input mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">未分类</SelectItem>{categories.data?.map(category => <SelectItem key={category.id} value={String(category.id)}>{category.name}</SelectItem>)}</SelectContent></Select></div><div><Label>发布状态</Label><Select value={form.status} onValueChange={value => setForm({ ...form, status: value as DreamForm["status"] })}><SelectTrigger className="admin-input mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">草稿</SelectItem><SelectItem value="published">已发布</SelectItem><SelectItem value="archived">已下架</SelectItem></SelectContent></Select></div><div><Label>标题</Label><Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="admin-input mt-2" placeholder="梦见月光照在河面" /></div><div><Label>URL 标识</Label><Input required value={form.slug} onChange={event => setForm({ ...form, slug: event.target.value.toLowerCase() })} className="admin-input mt-2" placeholder="moon-over-river" /></div><div className="md:col-span-2"><Label>摘要</Label><Textarea required value={form.summary} onChange={event => setForm({ ...form, summary: event.target.value })} className="admin-input mt-2 min-h-20" placeholder="用简短文字介绍梦境场景。" /></div><div className="md:col-span-2"><Label>完整释义</Label><Textarea required value={form.meaning} onChange={event => setForm({ ...form, meaning: event.target.value })} className="admin-input mt-2 min-h-28" placeholder="填写公开详情页展示的完整释义。" /></div><div><Label>幸运数字</Label><Input required value={form.luckyNumbers} onChange={event => setForm({ ...form, luckyNumbers: event.target.value })} className="admin-input mt-2" placeholder="01, 10" /></div><div><Label>图片链接（可选）</Label><Input value={form.imageUrl} onChange={event => setForm({ ...form, imageUrl: event.target.value })} className="admin-input mt-2" placeholder="https://…" /></div><div className="md:col-span-2"><Button disabled={create.isPending || update.isPending} className="bg-lime-200 text-[#09221c] hover:bg-lime-100">{create.isPending || update.isPending ? "正在保存…" : form.id ? "保存修改" : "创建条目"}</Button></div></form></div></section>
    <section className="mt-7">{dreams.isLoading ? <QueryLoading /> : dreams.isError ? <QueryError label="无法读取 Dream1000 管理列表。" onRetry={() => dreams.refetch()} /> : !dreams.data?.length ? <QueryEmpty label="尚未创建 Dream1000 条目" detail="先新建分类和条目，发布后即可让公开搜索与详情页读取。" /> : <div className="grid gap-4 lg:grid-cols-2">{dreams.data.map(({ entry, categoryName }) => <article key={entry.id} className="admin-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-lime-200">{categoryName ?? "未分类"}</p><h3 className="mt-2 text-lg font-black text-white">{entry.title}</h3><p className="mt-2 text-sm leading-6 text-emerald-50/58">{entry.summary}</p></div><span className={`status-pill status-${entry.status}`}>{entry.status === "draft" ? "草稿" : entry.status === "published" ? "已发布" : "已下架"}</span></div><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setForm({ id: entry.id, categoryId: entry.categoryId ? String(entry.categoryId) : "none", slug: entry.slug, title: entry.title, summary: entry.summary, meaning: entry.meaning, luckyNumbers: entry.luckyNumbers, imageUrl: entry.imageUrl ?? "", status: entry.status })} className="admin-action"><Edit3 className="mr-1.5 h-3.5 w-3.5" />编辑</Button>{entry.status !== "published" ? <Button size="sm" onClick={() => setStatus.mutate({ id: entry.id, status: "published" })} className="bg-lime-200 text-[#09221c] hover:bg-lime-100"><Send className="mr-1.5 h-3.5 w-3.5" />发布</Button> : <Button size="sm" variant="outline" onClick={() => setStatus.mutate({ id: entry.id, status: "archived" })} className="admin-action"><Trash2 className="mr-1.5 h-3.5 w-3.5" />下架</Button>}</div></article>)}</div>}</section>
  </AdminShell>;
}
