import { useState } from "react";
import { Edit3, Eye, FilePlus2, Send, Trash2 } from "lucide-react";
import { AdminShell } from "@/components/AdminShell";
import { AdminPageHeader } from "@/components/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { QueryEmpty, QueryError, QueryLoading } from "@/components/QueryState";
import { humanizeError, toLocalInput } from "@/lib/admin";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

type ResultForm = { id?: number; gameType: "2d" | "3d"; resultNumber: string; title: string; drawAt: string; sourceLabel: string; note: string; status: "draft" | "published" | "archived" };
const blankResult = (): ResultForm => ({ gameType: "2d", resultNumber: "", title: "", drawAt: toLocalInput(new Date()), sourceLabel: "", note: "", status: "draft" });

export default function AdminResults() {
  const { user, loading } = useAuth(); const canQueryAdmin = !loading && user?.role === "admin";
  const utils = trpc.useUtils(); const results = trpc.adminContent.results.list.useQuery(undefined, { enabled: canQueryAdmin });
  const [form, setForm] = useState<ResultForm>(blankResult); const [error, setError] = useState<string | null>(null);
  const save = trpc.adminContent.results.create.useMutation({ onSuccess: () => { setForm(blankResult()); setError(null); utils.adminContent.results.list.invalidate(); utils.adminContent.overview.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const update = trpc.adminContent.results.update.useMutation({ onSuccess: () => { setForm(blankResult()); setError(null); utils.adminContent.results.list.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const setStatus = trpc.adminContent.results.setStatus.useMutation({ onSuccess: () => { utils.adminContent.results.list.invalidate(); utils.adminContent.overview.invalidate(); }, onError: error => setError(humanizeError(error)) });
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError(null); const payload = { ...form, drawAt: new Date(form.drawAt) }; if (form.id) update.mutate({ ...payload, id: form.id }); else save.mutate(payload); };
  const busy = save.isPending || update.isPending;
  return <AdminShell><AdminPageHeader eyebrow="RESULT PUBLISHING" title="2D / 3D 结果管理" description="创建、编辑、发布或下架结果。公开页面只读取已发布状态。" />
    <section className="admin-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-bold text-white">{form.id ? "编辑结果" : "新增结果"}</h2>{form.id ? <Button variant="ghost" onClick={() => setForm(blankResult())} className="text-emerald-50/65 hover:text-white">取消编辑</Button> : <FilePlus2 className="h-5 w-5 text-lime-200" />}</div>{error ? <p className="mt-4 rounded-lg border border-red-300/25 bg-red-300/10 p-3 text-sm text-red-100">{error}</p> : null}<form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><div><Label>类型</Label><Select value={form.gameType} onValueChange={value => setForm({ ...form, gameType: value as "2d" | "3d" })}><SelectTrigger className="admin-input mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="2d">2D</SelectItem><SelectItem value="3d">3D</SelectItem></SelectContent></Select></div><div><Label>结果号码</Label><Input required maxLength={8} value={form.resultNumber} onChange={event => setForm({ ...form, resultNumber: event.target.value })} className="admin-input mt-2" placeholder="例如：123" /></div><div><Label>结果标题</Label><Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="admin-input mt-2" placeholder="例如：下午场结果" /></div><div><Label>开奖时间</Label><Input required type="datetime-local" value={form.drawAt} onChange={event => setForm({ ...form, drawAt: event.target.value })} className="admin-input mt-2" /></div><div><Label>来源说明</Label><Input value={form.sourceLabel} onChange={event => setForm({ ...form, sourceLabel: event.target.value })} className="admin-input mt-2" placeholder="可选" /></div><div><Label>初始状态</Label><Select value={form.status} onValueChange={value => setForm({ ...form, status: value as ResultForm["status"] })}><SelectTrigger className="admin-input mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">草稿</SelectItem><SelectItem value="published">已发布</SelectItem><SelectItem value="archived">已下架</SelectItem></SelectContent></Select></div><div className="md:col-span-2 xl:col-span-3"><Label>补充说明</Label><Textarea value={form.note} onChange={event => setForm({ ...form, note: event.target.value })} className="admin-input mt-2 min-h-24" placeholder="可选：结果补充说明或发布备注" /></div><div className="md:col-span-2 xl:col-span-3"><Button disabled={busy} className="bg-lime-200 text-[#09221c] hover:bg-lime-100">{busy ? "正在保存…" : form.id ? "保存修改" : "创建结果"}</Button></div></form></section>
    <section className="mt-7">{results.isLoading ? <QueryLoading /> : results.isError ? <QueryError label="无法读取结果管理列表。" onRetry={() => results.refetch()} /> : !results.data?.length ? <QueryEmpty label="尚未创建结果记录" detail="使用上方表单先创建草稿，审核后再发布到公开页面。" /> : <div className="overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[1.05fr_.9fr_.9fr_1fr] gap-3 bg-white/[.045] px-5 py-3 text-xs font-bold uppercase tracking-wider text-emerald-50/45"><span>结果</span><span>时间</span><span>状态</span><span>操作</span></div>{results.data.map(item => <div key={item.id} className="grid grid-cols-1 gap-4 border-t border-white/8 px-5 py-5 text-sm md:grid-cols-[1.05fr_.9fr_.9fr_1fr] md:items-center"><div><div className="inline-flex rounded-full bg-lime-200/12 px-2 py-1 text-xs font-bold text-lime-100">{item.gameType.toUpperCase()}</div><p className="mt-2 font-bold text-white">{item.title}</p><p className="font-display text-xl tracking-[.12em] text-emerald-50">{item.resultNumber}</p></div><p className="text-emerald-50/60">{formatDate(item.drawAt)}</p><p><span className={`status-pill status-${item.status}`}>{item.status === "draft" ? "草稿" : item.status === "published" ? "已发布" : "已下架"}</span></p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setForm({ id: item.id, gameType: item.gameType, resultNumber: item.resultNumber, title: item.title, drawAt: toLocalInput(item.drawAt), sourceLabel: item.sourceLabel ?? "", note: item.note ?? "", status: item.status })} className="admin-action"><Edit3 className="mr-1.5 h-3.5 w-3.5" />编辑</Button>{item.status !== "published" ? <Button size="sm" onClick={() => setStatus.mutate({ id: item.id, status: "published" })} className="bg-lime-200 text-[#09221c] hover:bg-lime-100"><Send className="mr-1.5 h-3.5 w-3.5" />发布</Button> : <Button size="sm" variant="outline" onClick={() => setStatus.mutate({ id: item.id, status: "archived" })} className="admin-action"><Trash2 className="mr-1.5 h-3.5 w-3.5" />下架</Button>}</div></div>)}</div>}</section>
  </AdminShell>;
}
