import { BadgeCheck, ClipboardCheck, ShieldCheck } from "lucide-react";
import { startLogin } from "@/const";
import { PublicShell } from "@/components/PublicShell";
import { QueryError, QueryLoading } from "@/components/QueryState";
import { Button } from "@/components/ui/button";
import { humanizeError } from "@/lib/admin";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export default function AgentHome() {
  const { user, loading } = useAuth();
  const canLoadAgent = !loading && user?.role === "agent";
  const agent = trpc.accounts.agent.me.useQuery(undefined, { enabled: canLoadAgent });
  return <PublicShell><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><p className="eyebrow">AGENT CONSOLE</p><h1 className="mt-4 font-display text-4xl font-black tracking-tight text-white sm:text-6xl">你的 SKY1688<br /><span className="text-lime-200">Agent 账户</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-emerald-50/65 sm:text-lg">这是已激活 Agent 的身份确认页。当前版本未加入佣金、余额、支付、转账或投注功能。</p>
    <section className="golden-panel mt-10 max-w-4xl p-6 sm:p-8">{loading ? <QueryLoading /> : !user ? <div className="text-center"><ShieldCheck className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-xl font-black text-white">请先登录</h2><p className="mt-2 text-sm leading-6 text-emerald-50/65">Agent 页面会验证 Manus 登录身份和已激活的 Agent 角色。</p><Button onClick={() => startLogin()} className="mt-6 bg-lime-200 text-[#09221c] hover:bg-lime-100">使用 Manus 登录</Button></div> : user.role !== "agent" ? <div className="text-center"><ClipboardCheck className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-xl font-black text-white">此账户尚未激活为 Agent</h2><p className="mt-2 text-sm leading-6 text-emerald-50/65">请让管理员先创建邀请，并使用与邀请邮箱一致的 Manus 登录后完成激活。</p><a href="/agent/activate" className="mt-6 inline-flex h-10 items-center justify-center bg-lime-200 px-4 text-sm font-bold text-[#09221c]">前往 Agent 激活</a></div> : agent.isLoading ? <QueryLoading /> : agent.isError ? <QueryError label={humanizeError(agent.error)} onRetry={() => agent.refetch()} /> : !agent.data ? <QueryError label="未找到与你的登录身份关联的 Agent 记录。" /> : <div><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime-200">ACTIVE AGENT</p><h2 className="mt-2 text-2xl font-black text-white">{agent.data.fullName}</h2><p className="mt-2 text-sm text-emerald-50/60">已通过管理员邀请与 Manus 邮箱完成身份关联。</p></div><BadgeCheck className="h-10 w-10 text-lime-200" /></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-50/45">Agent code</p><p className="mt-3 font-mono text-lg font-bold tracking-[.1em] text-lime-100">{agent.data.agentCode}</p></div><div className="border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-50/45">Account status</p><p className="mt-3 text-lg font-bold text-white">{agent.data.status === "active" ? "已激活" : "受限"}</p></div><div className="border border-white/10 bg-white/[.03] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-50/45">Access scope</p><p className="mt-3 text-sm leading-6 text-emerald-50/65">身份已启用。运营权限将仅在后续被明确授权的模块中开放。</p></div></div></div>}</section></div></PublicShell>;
}
