import { Link } from "wouter";
import { ArrowRight, CheckCircle2, MoonStar, Search, ShieldCheck, Sparkles } from "lucide-react";
import type { ComponentType } from "react";
import { Button } from "@/components/ui/button";
import { PublicShell } from "@/components/PublicShell";
import { QueryEmpty, QueryError, QueryLoading } from "@/components/QueryState";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";

const highlights: Array<{ title: string; copy: string; Icon: ComponentType<{ className?: string }> }> = [
  { title: "受保护发布", copy: "Manus 登录和管理员角色控制后台写入", Icon: ShieldCheck },
  { title: "公开读取", copy: "2D/3D 结果与 Dream1000 已通过公开 API 输出", Icon: Search },
  { title: "状态透明", copy: "草稿、已发布、下架三种内容状态", Icon: CheckCircle2 },
];

export default function Home() {
  const results = trpc.content.results.list.useQuery({ limit: 3 });
  const dreams = trpc.content.dreams.list.useQuery({ limit: 3 });
  return <PublicShell><section className="mx-auto max-w-7xl px-4 pb-20 pt-12 sm:px-6 lg:pt-18"><div className="hero-grid relative overflow-hidden rounded-[2.2rem] border border-lime-200/15 p-7 sm:p-11 lg:p-14"><div className="relative z-10 max-w-2xl"><p className="eyebrow">SKY1688 · GOLDEN MONEY</p><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-6xl">结果、梦境与内容发布，<span className="text-lime-200">清晰地聚在一起。</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-emerald-50/70">延续恢复的 SKY1688 / Golden Money 视觉方向，并以公开数据服务与受保护后台为内容发布基础。</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/results"><Button className="bg-lime-200 text-[#09221c] hover:bg-lime-100">查看 2D / 3D 结果 <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/dreams"><Button variant="outline" className="border-white/15 bg-white/[0.04] text-white hover:bg-white/10">浏览 Dream1000</Button></Link></div></div><div className="hero-moon" aria-hidden="true"><div className="moon-orbit orbit-a" /><div className="moon-orbit orbit-b" /><div className="grid h-32 w-32 place-items-center rounded-[2rem] border border-lime-100/35 bg-lime-200/20 shadow-[0_0_90px_rgba(184,255,80,.4)]"><MoonStar className="h-14 w-14 text-lime-100" /></div><span className="moon-chip chip-top">1000</span><span className="moon-chip chip-left">2D</span></div></div>
    <div className="mt-6 grid gap-3 md:grid-cols-3">{highlights.map(({ title, copy, Icon }) => <div key={title} className="golden-panel flex items-start gap-4 p-5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-lime-200/10 text-lime-200"><Icon className="h-5 w-5" /></div><div><h2 className="font-bold text-white">{title}</h2><p className="mt-1 text-sm leading-6 text-emerald-50/55">{copy}</p></div></div>)}</div>
    <section className="mt-18"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">LATEST PUBLISHED</p><h2 className="mt-3 text-3xl font-black text-white">最近结果</h2></div><Link href="/results" className="inline-flex items-center gap-1 text-sm font-bold text-lime-200 hover:text-lime-100">查看全部 <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6">{results.isLoading ? <QueryLoading /> : results.isError ? <QueryError onRetry={() => results.refetch()} /> : !results.data?.length ? <QueryEmpty label="尚无已发布结果" detail="后台发布内容后，这里会自动显示最新结果。" /> : <div className="grid gap-4 md:grid-cols-3">{results.data.map(result => <Link key={result.id} href={`/results/${result.id}`} className="golden-card p-5"><div className="flex items-center justify-between text-xs font-bold"><span className="rounded-full bg-lime-200 px-2.5 py-1 text-[#09221c]">{result.gameType.toUpperCase()}</span><span className="text-emerald-50/45">{formatDate(result.drawAt)}</span></div><p className="mt-8 text-sm text-emerald-50/65">{result.title}</p><p className="mt-2 font-display text-4xl font-black tracking-[0.14em] text-white">{result.resultNumber}</p></Link>)}</div>}</div></section>
    <section className="mt-18"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">DISCOVER DREAMS</p><h2 className="mt-3 text-3xl font-black text-white">Dream1000</h2></div><Link href="/dreams" className="inline-flex items-center gap-1 text-sm font-bold text-lime-200 hover:text-lime-100">开始搜索 <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6">{dreams.isLoading ? <QueryLoading /> : dreams.isError ? <QueryError onRetry={() => dreams.refetch()} /> : !dreams.data?.length ? <QueryEmpty label="Dream1000 正在等待内容发布" detail="管理员完成分类与条目发布后，公开搜索与详情阅读会自动启用。" /> : <div className="grid gap-4 md:grid-cols-3">{dreams.data.map((dream, index) => <Link key={dream.id} href={`/dreams/${dream.slug}`} className="golden-card overflow-hidden"><div className={`dream-card-top dream-shade-${(index % 3) + 1}`}><Sparkles className="absolute bottom-5 left-1/2 h-7 w-7 -translate-x-1/2 text-white" /></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-lime-200">{dream.luckyNumbers}</p><h3 className="mt-3 text-lg font-black text-white">{dream.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-emerald-50/55">{dream.summary}</p></div></Link>)}</div>}</div></section>
  </section></PublicShell>;
}
