import { ArrowRight, CircleCheck, LockKeyhole, UserRound } from "lucide-react";
import { startLogin } from "@/const";
import { PublicShell } from "@/components/PublicShell";
import { QueryError, QueryLoading } from "@/components/QueryState";
import { Button } from "@/components/ui/button";
import { humanizeError } from "@/lib/admin";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

export default function PlayerAccount() {
  const { user, loading } = useAuth();
  const canLoadProfile = !loading && user?.role === "user";
  const profile = trpc.accounts.player.me.useQuery(undefined, { enabled: canLoadProfile });
  return <PublicShell><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-3xl"><p className="eyebrow">PLAYER ACCOUNT</p><h1 className="mt-4 font-display text-4xl font-black tracking-tight text-white sm:text-6xl">你的 SKY1688<br /><span className="text-lime-200">Player 账户</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-emerald-50/65 sm:text-lg">Player 账户用于保存个人公开内容访问身份。当前版本不包含钱包、支付、转账或投注功能。</p></div>
    <section className="golden-panel mt-10 max-w-3xl p-6 sm:p-8">{loading ? <QueryLoading /> : !user ? <div className="text-center"><LockKeyhole className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-2xl font-black text-white">请先使用 Manus 登录</h2><p className="mt-3 text-sm leading-6 text-emerald-50/65">登录后可开始 Player onboarding，并显示已审核公开内容的快捷入口。</p><Button onClick={() => startLogin()} className="mt-6 bg-lime-200 text-[#09221c] hover:bg-lime-100">使用 Manus 登录<ArrowRight className="ml-2 h-4 w-4" /></Button></div> : user.role === "agent" ? <div className="text-center"><UserRound className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-2xl font-black text-white">此账号已激活为 Agent</h2><p className="mt-3 text-sm leading-6 text-emerald-50/65">Agent 和 Player 身份分离；请使用未被激活为 Agent 的 Manus 账号访问 Player 页面。</p></div> : user.role === "admin" ? <div className="text-center"><UserRound className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-2xl font-black text-white">管理员账号不使用 Player 页面</h2><p className="mt-3 text-sm leading-6 text-emerald-50/65">管理员可以从后台创建 Agent 邀请、管理公开结果和 Dream1000 内容。</p></div> : profile.isLoading ? <QueryLoading /> : profile.isError ? <QueryError label={humanizeError(profile.error)} onRetry={() => profile.refetch()} /> : !profile.data ? <div className="text-center"><UserRound className="mx-auto h-8 w-8 text-lime-200" /><h2 className="mt-4 text-2xl font-black text-white">先激活 Player profile</h2><p className="mt-3 text-sm leading-6 text-emerald-50/65">激活后，此账号可在此页面查看身份状态，并进入已审核的公开内容。</p><a href="/player/activate" className="mt-6 inline-flex h-10 items-center justify-center bg-lime-200 px-4 text-sm font-bold text-[#09221c]">开始 Player onboarding</a></div> : <div><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime-200">ACTIVE PROFILE</p><h2 className="mt-2 text-2xl font-black text-white">{profile.data.displayName || user.name || "SKY1688 Player"}</h2><p className="mt-2 text-sm text-emerald-50/60">Manus 登录身份已验证 · Profile 状态：已启用</p></div><CircleCheck className="h-10 w-10 text-lime-200" /></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><a href="/results" className="group border border-white/10 bg-white/[.03] p-5"><p className="text-sm font-bold text-white">查看 2D / 3D 结果</p><p className="mt-2 text-sm leading-6 text-emerald-50/55">阅读后台已审核、已发布的结果内容。</p><span className="mt-4 inline-flex items-center text-sm font-bold text-lime-200">前往结果 <ArrowRight className="ml-1 h-4 w-4" /></span></a><a href="/dreams" className="group border border-white/10 bg-white/[.03] p-5"><p className="text-sm font-bold text-white">浏览 Dream1000</p><p className="mt-2 text-sm leading-6 text-emerald-50/55">按关键词、分类或幸运数字查阅已发布梦境条目。</p><span className="mt-4 inline-flex items-center text-sm font-bold text-lime-200">前往 Dream1000 <ArrowRight className="ml-1 h-4 w-4" /></span></a></div></div>}</section></div></PublicShell>;
}
